### ISSUE TITLE
Why have all the released version been removed?

### ISSUE THREAD

**Issue by crumb1e** [elevate-digital/nova-charcounted-fields#1]
Hey!

I noticed that a few of our nova packages that make use of these charcounted fields have been failing to install as they were requiring `^2.0`, I have moved them all to `dev-master` and its sorted. 

But I was just wondering why you did this? I'm sure there are a lot of people who have ran into this hurdle, and it was a bit annoying trying to figure out what had happened.

Thanks 😄

**Comment by Stanleydevv** [comment]
Hey,

The organization moved to gitlab for private projects. My colleague wasn't aware of the public projects.

Sorry for the lost time and it won't happen again :)

Thanks for using the project
